// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9dswk2b9l5VqnWpetal_k3BFhkIpuP7o',
    appId: '1:305959473025:web:ab718fc60a16bac0f72280',
    messagingSenderId: '305959473025',
    projectId: 'rarevault-ecommerce',
    authDomain: 'rarevault-ecommerce.firebaseapp.com',
    storageBucket: 'rarevault-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcODkMUDsIU2ajYmGOXgvTQf8zTrwa8KA',
    appId: '1:305959473025:android:93063b4567e13f79f72280',
    messagingSenderId: '305959473025',
    projectId: 'rarevault-ecommerce',
    storageBucket: 'rarevault-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3HDPbrmFqwKG65QxtMo33QFgRjP6x7N8',
    appId: '1:305959473025:ios:ae00b18df58acf06f72280',
    messagingSenderId: '305959473025',
    projectId: 'rarevault-ecommerce',
    storageBucket: 'rarevault-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.rarevaultEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3HDPbrmFqwKG65QxtMo33QFgRjP6x7N8',
    appId: '1:305959473025:ios:ae00b18df58acf06f72280',
    messagingSenderId: '305959473025',
    projectId: 'rarevault-ecommerce',
    storageBucket: 'rarevault-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.rarevaultEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9dswk2b9l5VqnWpetal_k3BFhkIpuP7o',
    appId: '1:305959473025:web:dd8c162018690acef72280',
    messagingSenderId: '305959473025',
    projectId: 'rarevault-ecommerce',
    authDomain: 'rarevault-ecommerce.firebaseapp.com',
    storageBucket: 'rarevault-ecommerce.firebasestorage.app',
  );
}
